language: objective-c
osx_image: xcode8

env:
  - PLATFORM=Mac     DESTINATION='platform=OS X'
  - PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 6S'

script:
  - xcodebuild -version
  - xcodebuild -project SwiftyAttributes.xcodeproj -scheme SwiftyAttributes -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test
  - bash <(curl -s https://codecov.io/bash) -cF ios